/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Logic.Game;
import java.awt.Color;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;

/**
 * Grafické okno které zobrazuje běžící hru a stará se o základní logiku hry.
 *
 * @author Miloslav Fico
 */
public class PanelGame extends javax.swing.JFrame {

    /**
     * Creates new form PanelGame
     */
    Game game;
    UI ui;

    int positionOfButton;
    int[] valuesFromButtons;

    JButton[] buttons;

    public PanelGame() {
        initComponents();

    }

    public PanelGame(Game game, UI ui) {
        this.game = game;
        this.ui = ui;
        valuesFromButtons = new int[2];

        initComponents();
        setGamePanel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GameArea = new javax.swing.JPanel();
        jNameOfLocalPlayer = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        jLocalPlayerElo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNameOfSecondPlayer = new javax.swing.JLabel();
        jSecondPlayerElo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLocalPlayerScore = new javax.swing.JLabel();
        jSecondPlayerScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout GameAreaLayout = new javax.swing.GroupLayout(GameArea);
        GameArea.setLayout(GameAreaLayout);
        GameAreaLayout.setHorizontalGroup(
            GameAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        GameAreaLayout.setVerticalGroup(
            GameAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        jNameOfLocalPlayer.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jNameOfLocalPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNameOfLocalPlayer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 54)); // NOI18N
        jLabel2.setText("VS");
        jLabel2.setToolTipText("");

        jLocalPlayerElo.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLocalPlayerElo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLocalPlayerElo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elo");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Elo");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Oponent");

        jNameOfSecondPlayer.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jNameOfSecondPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSecondPlayerElo.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jSecondPlayerElo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSecondPlayerElo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hrač");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Score");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Score");

        jLocalPlayerScore.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLocalPlayerScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSecondPlayerScore.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jSecondPlayerScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNameOfLocalPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLocalPlayerElo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLocalPlayerScore, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(GameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(39, 39, 39))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSecondPlayerScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNameOfSecondPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSecondPlayerElo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jNameOfSecondPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSecondPlayerElo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jSecondPlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jNameOfLocalPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLocalPlayerElo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLocalPlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelGame().setVisible(true);
            }
        });
    }

    public void setGamePanel() {
        buttons = new JButton[16];
        jLocalPlayerElo.setText(String.valueOf(game.getLoclalPlayer().getElo()));
        jNameOfLocalPlayer.setText(game.getLoclalPlayer().getName());
        jSecondPlayerElo.setText(String.valueOf(game.getSecondPlayer().getElo()));
        jNameOfSecondPlayer.setText(game.getSecondPlayer().getName());
        setScores();

        GridLayout gl = new GridLayout(4, 4);
        GameArea.setLayout(gl);

        for (int j = 0; j <= buttons.length - 1; j++) {
            buttons[j] = new JButton("..");
            int position = j;
            buttons[j].addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    positionOfButton = position;
                    cardClicked();
                }
            });

        }

        for (int i = 0; i < buttons.length; i++) {
            GameArea.add(buttons[i]);
        }

    }

    public void cardClicked() {

        buttons[positionOfButton].setEnabled(false);
       System.out.println(game.getField().getMove());
        if (game.getField().getMove() == 2) {

            game.getField().moveReset();
            if (game.getField().compareTwoCards(game.getField().getCard(valuesFromButtons[0]), game.getField().getCard(valuesFromButtons[1]))) {
                game.getField().getCard(valuesFromButtons[0]).setClickable(false);
                game.getField().getCard(valuesFromButtons[1]).setClickable(false);
            } else {
                ui.setPlayerTurn(false);
                setAllCardsToBackside();
            }

        } else {

            buttons[positionOfButton].setText(String.valueOf(game.getField().getCard(positionOfButton).getValue()));
            valuesFromButtons[game.getField().getMove()] = positionOfButton;
            game.getField().getCard(positionOfButton).setFlip(true);
            game.getField().nextMove();

        }

        ui.nextTurn();
        ui.isGameWon();
    }

    public void setButtonsForFirstTime() {
        for (int i = 0; i < buttons.length; i++) {
            buttons[i].setEnabled(ui.isPlayerTurn());
        }
    }

    public void setAllButtonsAvailability() {

        for (int i = 0; i < game.getField().getField().size(); i++) {
            if (!game.getField().getCard(i).isFlipped()) {
                buttons[i].setEnabled(ui.isPlayerTurn());
            }

        }

        for (int i = 0; i < game.getField().getField().size(); i++) {
            if (game.getField().getCard(i).isClickable() == false) {
                buttons[i].setBackground(Color.black);
                buttons[i].setEnabled(false);
            }
        }
    }

    public void setButtonsValue() {
        if (!ui.isPlayerTurn()) {
            for (int i = 0; i < game.getField().getField().size(); i++) {
                if (game.getField().getCard(i).isFlipped()) {
                    buttons[i].setText(String.valueOf(game.getField().getCard(i).getValue()));
                }
            }
        }

    }

    public void setAllCardsToBackside() {
        for (int i = 0; i < game.getField().getField().size(); i++) {
            game.getField().getCard(i).setFlip(false);
        }
        for (JButton button : buttons) {
            button.setText("..");

        }
    }

    public void setScores() {
        jLocalPlayerScore.setText(String.valueOf(game.getLoclalPlayer().getScore()));
        jSecondPlayerScore.setText(String.valueOf(game.getSecondPlayer().getScore()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GameArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLocalPlayerElo;
    private javax.swing.JLabel jLocalPlayerScore;
    private javax.swing.JLabel jNameOfLocalPlayer;
    private javax.swing.JLabel jNameOfSecondPlayer;
    private javax.swing.JLabel jSecondPlayerElo;
    private javax.swing.JLabel jSecondPlayerScore;
    // End of variables declaration//GEN-END:variables
}
